module.exports = [
  ['int', 'id']
  ['int', 'map']
  ['int', 'parent']
  ['int', 'unk0'] # "internal index?"
  ['int', 'flags']
  ['int', 'unk1']
  ['int', 'unk2']
  ['int', 'ambience']
  ['int', 'music']
  ['int', 'intro_music']
  ['int', 'level']
  ['string', 'name']
  ['localization']
  ['int', 'faction']
  ['int', 'unk3']
  ['int', 'unk4']
  ['int', 'unk5']
  ['int', 'unk6']
]