module.exports = [
  ['int', 'id']
  ['byte', 'race']
  ['byte', 'class']
  ['byte', 'gender']
  ['byte', 'unk'] # always zero

  ['int', 'item_id_1']
  ['int', 'item_id_2']
  ['int', 'item_id_3']
  ['int', 'item_id_4']
  ['int', 'item_id_5']
  ['int', 'item_id_6']
  ['int', 'item_id_7']
  ['int', 'item_id_8']
  ['int', 'item_id_9']
  ['int', 'item_id_10']
  ['int', 'item_id_11']
  ['int', 'item_id_12']
  ['int', 'item_display_id_1']
  ['int', 'item_display_id_2']
  ['int', 'item_display_id_3']
  ['int', 'item_display_id_4']
  ['int', 'item_display_id_5']
  ['int', 'item_display_id_6']
  ['int', 'item_display_id_7']
  ['int', 'item_display_id_8']
  ['int', 'item_display_id_9']
  ['int', 'item_display_id_10']
  ['int', 'item_display_id_11']
  ['int', 'item_display_id_12']
  ['int', 'item_slot_1']
  ['int', 'item_slot_2']
  ['int', 'item_slot_3']
  ['int', 'item_slot_4']
  ['int', 'item_slot_5']
  ['int', 'item_slot_6']
  ['int', 'item_slot_7']
  ['int', 'item_slot_8']
  ['int', 'item_slot_9']
  ['int', 'item_slot_10']
  ['int', 'item_slot_11']
  ['int', 'item_slot_12']
]
