module.exports = [
  ['int', 'id']
  ['string', 'name']
  ['localization']
  ['int', 'item_1']
  ['int', 'item_2']
  ['int', 'item_3']
  ['int', 'item_4']
  ['int', 'item_5']
  ['int', 'item_6']
  ['int', 'item_7']
  ['int', 'item_8']
  ['int', 'item_9']
  ['int', 'item_10']
  ['null']
  ['null']
  ['null']
  ['null']
  ['null']
  ['null']
  ['null']
  ['int', 'spell_1']
  ['int', 'spell_2']
  ['int', 'spell_3']
  ['int', 'spell_4']
  ['int', 'spell_5']
  ['int', 'spell_6']
  ['int', 'spell_7']
  ['int', 'spell_8']
  ['int', 'bonus_1']
  ['int', 'bonus_2']
  ['int', 'bonus_3']
  ['int', 'bonus_4']
  ['int', 'bonus_5']
  ['int', 'bonus_6']
  ['int', 'bonus_7']
  ['int', 'bonus_8']
  ['int', 'skill_line']
  ['int', 'req_skill_level']
]