module.exports = [
  ['int', 'id']
  ['string', 'model_left']
  ['string', 'model_right']
  ['string', 'texture_left']
  ['string', 'texture_right']
  ['string', 'icon_name']
  ['int', 'geoset_flag0']
  ['int', 'geoset_flag1']
  ['int', 'geoset_flag2']
  ['int', 'geoset_flag3']
  ['int', 'unk0']
  ['int', 'item_group_sounds']
  ['int', 'helmet_geoset_vis_data0']
  ['int', 'helmet_geoset_vis_data1']
  ['string', 'texture_arm_upper']
  ['string', 'texture_arm_lower']
  ['string', 'texture_hand']
  ['string', 'texture_torso_upper']
  ['string', 'texture_torso_lower']
  ['string', 'texture_leg_upper']
  ['string', 'texture_leg_lower']
  ['string', 'texture_foot']
  ['int', 'item_visuals']
]