module.exports = [
  ['uint', 'id']
  ['int', 'skill_line']
  ['uint', 'races']
  ['uint', 'classes']
  ['uint', 'flags']
  ['int', 'req_level']
  ['int', 'skill_tier_id']
  ['int', 'skill_cost_id']
]
