module.exports = [
  ['int', 'id']
  ['int', 'resistances_id']
  ['int', 'category']
  ['int', 'unk1']
  ['int', 'dispel_type']
  ['int', 'spell_mechanic']
  ['uint', 'unk2']
  ['uint', 'unk3']
  ['uint', 'targets']
  ['uint', 'unk4']
  ['int', 'unk5']
  ['uint', 'shapeshift_usable_mask']
  ['uint', 'shapeshift_unusable_mask'] #?
  ['int', 'unk6']
  ['uint', 'creature_type']
  ['int', 'spell_focus_object']
  ['int', 'caster_aura_state']
  ['int', 'target_aura_state']
  ['int', 'spell_cast_time']
  ['int', 'category_recovery_time']
  ['int', 'recovery_time']
  ['uint', 'interupt_flags']
  ['uint', 'aura_interupt_flags']
  ['uint', 'channel_interupt_flags']
  ['uint', 'proc_flags']
  ['int', 'proc_chance']
  ['int', 'proc_charges']
  ['int', 'level_max']
  ['int', 'level_base']
  ['int', 'level_spell']
  ['int', 'spell_duration']
  ['int', 'power_type']
  ['int', 'mana_cost']
  ['int', 'mana_cost_per_level']
  ['int', 'mana_per_second']
  ['int', 'mana_per_second_per_level']
  ['int', 'spell_range']
  ['float', 'projectile_speed']
  ['int', 'modal_next_spell']
  ['int', 'stack_amount']
  ['int', 'totem_1'] 
  ['int', 'totem_2']
  ['int', 'reagent_1']
  ['int', 'reagent_2']  
  ['int', 'reagent_3']   
  ['int', 'reagent_4']   
  ['int', 'reagent_5']   
  ['int', 'reagent_6']   
  ['int', 'reagent_7']   
  ['int', 'reagent_8']   
  ['int', 'reagent_count_1'] 
  ['int', 'reagent_count_2']    
  ['int', 'reagent_count_3']    
  ['int', 'reagent_count_4']    
  ['int', 'reagent_count_5']    
  ['int', 'reagent_count_6']    
  ['int', 'reagent_count_7']    
  ['int', 'reagent_count_8']    
  ['uint', 'iRefMask_ItemClass']   
  ['uint', 'iRefMask_ItemSubClass']      
  ['uint', 'iRefMask_InventorySlots']
  ['int', 'effect_1_id']
  ['int', 'effect_2_id']
  ['int', 'effect_3_id']
  ['int', 'effect_1_die_sides']
  ['int', 'effect_2_die_sides']
  ['int', 'effect_3_die_sides']
  ['int', 'effect_1_base_dice']
  ['int', 'effect_2_base_dice']
  ['int', 'effect_3_base_dice']
  ['int', 'effect_1_dice_per_level']
  ['int', 'effect_2_dice_per_level']
  ['int', 'effect_3_dice_per_level']
  ['float', 'effect_1_real_points_per_level']
  ['float', 'effect_2_real_points_per_level']
  ['float', 'effect_3_real_points_per_level']
  ['int', 'effect_1_base_points']
  ['int', 'effect_2_base_points']
  ['int', 'effect_3_base_points']
  ['int', 'effect_1_mechanic_id']
  ['int', 'effect_2_mechanic_id']
  ['int', 'effect_3_mechanic_id']
  ['int', 'effect_1_implicit_target_a']
  ['int', 'effect_2_implicit_target_a']
  ['int', 'effect_3_implicit_target_a']
  ['int', 'effect_1_implicit_target_b']
  ['int', 'effect_2_implicit_target_b']
  ['int', 'effect_3_implicit_target_b']
  ['int', 'effect_1_radius']
  ['int', 'effect_2_radius']
  ['int', 'effect_3_radius']
  ['int', 'effect_1_aura']
  ['int', 'effect_2_aura']
  ['int', 'effect_3_aura']
  ['int', 'effect_1_amplitude'] 
  ['int', 'effect_2_amplitude'] 
  ['int', 'effect_3_amplitude'] 
  ['float', 'effect_1_proc_value']
  ['float', 'effect_2_proc_value']
  ['float', 'effect_3_proc_value']
  ['int', 'effect_1_chain_target']
  ['int', 'effect_2_chain_target']
  ['int', 'effect_3_chain_target']
  ['int', 'effect_1_item_type']
  ['int', 'effect_2_item_type']
  ['int', 'effect_3_item_type']
  ['int', 'effect_1_misc_value']
  ['int', 'effect_2_misc_value']
  ['int', 'effect_3_misc_value']
  ['int', 'effect_1_trigger_spell']    
  ['int', 'effect_2_trigger_spell']    
  ['int', 'effect_3_trigger_spell']    
  ['float', 'effect_1_proc_chance']
  ['float', 'effect_2_proc_chance']
  ['float', 'effect_3_proc_chance']
  ['int', 'iRefID_SpellVisual']
  ['int', 'unk7']
  ['int', 'spell_icon']  
  ['int', 'iRefID_SpellIcon']    
  ['int', 'spell_priority']
  ['string', 'name']
  ['localization']







  ['string', 'rank']
  ['localization']







  ['string', 'description']
  ['localization']







  ['string', 'buff_desciption']
  ['localization']







  ['int', 'mana_cost_percent']
  ['int', 'start_recovery_category']
  ['int', 'start_recovery_time']
  ['int', 'affected_target_level']
  ['int', 'classes']
  ['uint', 'unk8']   
  ['int', 'spell_targets']  
  ['uint', 'unk9']
  ['int', 'dmg_class']
  ['int', 'unk10']
  ['int', 'unk11']
  ['float', 'dmg_multiplier_1']
  ['float', 'dmg_multiplier_2']
  ['float', 'dmg_multiplier_3']
  ['int', 'unk12']   
  ['int', 'unk13']   
  ['int', 'unk14']
]

###
module.exports = [
  ['uint', 'id']
  ['uint', 'school']
  ['uint', 'category']
  ['uint', 'cast_ui']
  ['uint', 'dispel_type']
  ['uint', 'mechanic']
  ['uint', 'attributes']
  ['uint', 'attributesEx']
  ['uint', 'attributesEx2']
  ['uint', 'attributesEx3']
  ['uint', 'attributesEx4']
  ['uint', 'stances']
  ['uint', 'stances_not'] #?
  ['uint', 'targets']
  ['uint', 'target_creature_type']
  ['uint', 'spell_focus_object']
  ['uint', 'caster_aura_state']
  ['uint', 'target_aura_state']
  ['uint', 'spell_cast_time']
  ['uint', 'recovery_time']
  ['uint', 'category_recovery_time']
  ['uint', 'interupt_flags']
  ['uint', 'aura_interupt_flags']
  ['uint', 'channel_interupt_flags']
  ['uint', 'proc_flags']
  ['uint', 'proc_chance']
  ['uint', 'proc_charges']
  ['uint', 'level_max']
  ['uint', 'level_base']
  ['uint', 'level_spell']
  ['uint', 'spell_duration']
  ['uint', 'power_type']
  ['uint', 'mana_cost']
  ['uint', 'mana_cost_per_level']
  ['uint', 'mana_per_second']
  ['uint', 'mana_per_second_per_level']
  ['uint', 'spell_range']
  ['float', 'projectile_speed']
  ['uint', 'modal_next_spell']
  ['uint', 'stack_amount']
  ['uint', 'totem_1'] 
  ['uint', 'totem_2']
  ['int', 'iRefID_Reagent_1']
  ['int', 'iRefID_Reagent_2']  
  ['int', 'iRefID_Reagent_3']   
  ['int', 'iRefID_Reagent_4']   
  ['int', 'iRefID_Reagent_5']   
  ['int', 'iRefID_Reagent_6']   
  ['int', 'iRefID_Reagent_7']   
  ['int', 'iRefID_Reagent_8']   
  ['uint', 'reagent_count_1'] 
  ['uint', 'reagent_count_2']    
  ['uint', 'reagent_count_3']    
  ['uint', 'reagent_count_4']    
  ['uint', 'reagent_count_5']    
  ['uint', 'reagent_count_6']    
  ['uint', 'reagent_count_7']    
  ['uint', 'reagent_count_8']    
  ['int', 'iRefMask_ItemClass']   
  ['int', 'iRefMask_ItemSubClass']      
  ['int', 'iRefMask_InventorySlots']
  ['uint', 'effect_1_id']
  ['uint', 'effect_2_id']
  ['uint', 'effect_3_id']
  ['int', 'effect_1_die_sides']
  ['int', 'effect_2_die_sides']
  ['int', 'effect_3_die_sides']
  ['uint', 'effect_1_base_dice']
  ['uint', 'effect_2_base_dice']
  ['uint', 'effect_3_base_dice']
  ['float', 'effect_1_dice_per_level']
  ['float', 'effect_2_dice_per_level']
  ['float', 'effect_3_dice_per_level']
  ['float', 'effect_1_real_points_per_level']
  ['float', 'effect_2_real_points_per_level']
  ['float', 'effect_3_real_points_per_level']
  ['int', 'effect_1_base_points']
  ['int', 'effect_2_base_points']
  ['int', 'effect_3_base_points']
  ['uint', 'effect_1_mechanic_id']
  ['uint', 'effect_2_mechanic_id']
  ['uint', 'effect_3_mechanic_id']
  ['uint', 'effect_1_implicit_target_a']
  ['uint', 'effect_2_implicit_target_a']
  ['uint', 'effect_3_implicit_target_a']
  ['uint', 'effect_1_implicit_target_b']
  ['uint', 'effect_2_implicit_target_b']
  ['uint', 'effect_3_implicit_target_b']
  ['uint', 'effect_1_radius']
  ['uint', 'effect_2_radius']
  ['uint', 'effect_3_radius']
  ['uint', 'effect_1_aura']
  ['uint', 'effect_2_aura']
  ['uint', 'effect_3_aura']
  ['uint', 'effect_1_amplitude'] 
  ['uint', 'effect_2_amplitude'] 
  ['uint', 'effect_3_amplitude'] 
  ['float', 'effect_1_proc_value']
  ['float', 'effect_2_proc_value']
  ['float', 'effect_3_proc_value']
  ['uint', 'effect_1_chain_target']
  ['uint', 'effect_2_chain_target']
  ['uint', 'effect_3_chain_target']
  ['uint', 'effect_1_item_type']
  ['uint', 'effect_2_item_type']
  ['uint', 'effect_3_item_type']
  ['int', 'effect_1_misc_value']
  ['int', 'effect_2_misc_value']
  ['int', 'effect_3_misc_value']
  ['uint', 'effect_1_trigger_spell']    
  ['uint', 'effect_2_trigger_spell']    
  ['uint', 'effect_3_trigger_spell']    
  ['float', 'effect_1_proc_chance']
  ['float', 'effect_2_proc_chance']
  ['float', 'effect_3_proc_chance']
  ['uint', 'spell_visual']
  ['uint', 'spell_visual2']
  ['uint', 'spell_icon']  
  ['uint', 'active_spell_icon']    
  ['uint', 'spell_priority']
  ['string', 'name']
  ['localization']







  ['string', 'rank']
  ['localization']







  ['string', 'description']
  ['localization']







  ['string', 'tooltip']
  ['localization']







  ['uint', 'mana_cost_percent']
  ['uint', 'start_recovery_category']
  ['uint', 'start_recovery_time']
  ['uint', 'max_target_level']
  ['uint', 'spell_family_name']
  ['uint', 'spell_family_flags']
  ['uint', 'max_targets']  
  ['uint', 'dmg_class']
  ['uint', 'prevention_type']
  ['uint', 'stance_bar_order']
  ['float', 'dmg_multiplier_1']
  ['float', 'dmg_multiplier_2']
  ['float', 'dmg_multiplier_3']
  ['uint', 'min_faction_id']   
  ['uint', 'min_reputation_id']   
  ['uint', 'min_reputation']
  ['uint', 'required_aura_vision'] #added build 5965
]
###