module.exports = [
  ['int', 'id']
  ['int', 'root_id']
  ['int', 'name_set']
  ['int', 'group_id']
  ['int', 'unk0']
  ['int', 'unk1']
  ['int', 'unk2']
  ['int', 'unk3']
  ['int', 'unk4']
  ['int', 'flags']
  ['int', 'area_table']
  ['string', 'name']
  ['localization']
]