module.exports = [
  ['int', 'id']
  ['int', 'map']
  ['int', 'boundary_left']
  ['int', 'boundary_right']
  ['int', 'boundary_top']
  ['int', 'boundary_bottom']
  ['float', 'offset_x']
  ['float', 'offset_y']
  ['float', 'scale']
  ['float', 'taxi_min_x']
  ['float', 'taxi_min_y']
  ['float', 'taxi_max_x']
  ['float', 'taxi_max_y']
]